/*
LEEWAY HEADER — DO NOT REMOVE

REGION: AI.BEAST.COGNITION
TAG: AI.BEAST.CORE_SYNAPSE

COLOR_ONION_HEX:
NEON=#39FF14
FLUO=#0DFF94
PASTEL=#E8F5E9

ICON_ASCII:
family=lucide
glyph=zap

5WH:
WHAT = BEAST AI Core Cognition Layer
WHY = Provides 100% agent-driven deterministic response logic for students
WHO = Leeway Innovations (By Leonard Jerome Lee)
WHERE = src/services/ai.ts
WHEN = 2026-04-21
HOW = Local knowledge retrieval and agent routing

AGENTS:
VECTOR
ARIA
WARD
GOVERNOR

LICENSE:
MIT
*/

import { agentLeeRuntimeBootstrap } from 'leeway-sdk/src/core/AgentLeeRuntimeBootstrap';
import { agentOrchestrationPipeline } from 'leeway-sdk/src/core/AgentOrchestrationPipeline';
import { eventBus } from 'leeway-sdk/src/core/EventBus';
import { AgentLee } from 'leeway-sdk/src/agents/legacy/AgentLee';
import { voiceSession } from 'leeway-sdk/src/core/UnifiedVoiceSession';
import { leewayVoiceClient } from 'leeway-sdk/src/core/LeewayVoiceClient';

/**
 * BEAST AI - CORE COGNITION
 * Powered by Leeway Innovations
 * ACTUATED BY LEEWAY SDK AGENTIC OS
 */

interface AgentResponse {
  agent: string;
  text: string;
  code?: string;
  directives?: string[];
}

export const AGENT_HIERARCHY = {
  VECTOR: "Network/Diagnostics - Monitoring RTT and Bitrate.",
  ARIA: "Voice/Audio Studio - TTS and Emotion Inference.",
  WARD: "System Janitor - Memory and Cache cleanup.",
  GOVERNOR: "System Overlord - Licensing and Structural Integrity.",
};

export async function askAssistant(question: string, context: string): Promise<string> {
  console.log('[AI Service] Routing through Leeway Orchestration Pipeline:', { question });

  try {
    // Ensure Leeway SDK is initialized
    const state = agentLeeRuntimeBootstrap.getState();
    if (state.phase !== 'ready') {
      console.log('[AI Service] Initializing Leeway Runtime...');
      await agentLeeRuntimeBootstrap.initialize();
    }

    // Process through the Lead Orchestrator
    const result = await AgentLee.respond(question, { task: 'General Inquiry', style: 'normal' } as any);
    
    return result;
  } catch (error) {
    console.error('[AI Service] Leeway Mission Failure:', error);
    return `[SYSTEM_ALERT]: Leeway SDK link failed. Error: ${error instanceof Error ? error.message : 'Unknown integrity breach'}.`;
  }
}

export async function generateSpeech(text: string): Promise<string | null> {
  // Use Aria agent from the SDK for speech generation
  eventBus.emit('agent:thinking' as any, { message: 'ARIA_AGENT: Routing to Voice Studio...' });
  
  return new Promise((resolve) => {
    if (!leewayVoiceClient.isConnected) {
        leewayVoiceClient.connect('dummy-key', {
            onMessage: (msg) => {
                if (msg.audioBase64) {
                    resolve(msg.audioBase64);
                }
            }
        }).then(() => {
            leewayVoiceClient.sendText(text);
        }).catch(() => resolve(null));
    } else {
        leewayVoiceClient.sendText(text);
        // This is a simplified mock-up; in a real SDK, we'd have a more robust request-response mapping
        // For now, we'll assume the next audio message is for this text
    }
  });
}

export async function startVoiceSession() {
    console.log('[AI Service] Activating Unified Voice Session prowess...');
    await voiceSession.start();
}

export async function stopVoiceSession() {
    console.log('[AI Service] Deactivating Unified Voice Session...');
    await voiceSession.stop();
}

export async function workshopResponse(input: string, persona: string) {
  // Use AgentLee's planning and verification logic
  const plan = await AgentLee.plan(input);
  return `[BEAST_WORKSHOP]: Plan generated by Lee Prime:\n${plan}`;
}

// Subscription helper for UI components to listen to real-time agent broadcasts
export function subscribeToAgentEvents(callback: (event: any) => void) {
  const events = [
    'agent:active',
    'agent:done',
    'agent:thinking',
    'agent:speaking',
    'agent:error',
    'perception:voice-listening',
    'perception:voice-final',
    'runtime:ready'
  ];

  const unsubscribes = events.map(eventName => {
    return eventBus.on(eventName as any, (data: any) => {
      callback({ type: eventName, ...data });
    });
  });

  return () => {
    unsubscribes.forEach(unsub => unsub());
  };
}
